services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: minthantko/redhair-backend:latest
    ports:
      - 8999:8080
    environment:
      - JAVA_PROFILE=prod,db
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:3