# Top-level key 'spring'
spring:
  profiles:
    active:
      - db
  application:
    name: 331-backend
  datasource:
    url: jdbc:mysql://db:3306/selabdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop #I changed to create-drop for a while, to also drop schema
  # 'servlet' is a child of the top-level 'spring' key
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

supabase:
  storage:
    endpoint: https://pkpfakmiycauobjyogov.storage.supabase.co/storage/v1/s3
    endpoint_output: https://pkpfakmiycauobjyogov.storage.supabase.co/storage/v1/object/public
    bucket: redhair
    region: ap-southeast-1
    accessKey: 6d1828d0f5e3840270794a8ee176258d
    secretKey: 8b015d5e1e4e0e86436d87282284ec6d20777a69e5bde4e40dd13c354829701f

application:
  security:
    jwt:
      secret-key: 45ca55b5d46e1967633b8876bc9dccf2ff3f67591e4ca2822cf646cce3179b857e4b32186a8f4c5a191ef9c787e94608a5891da2259ba9419bce2e88cea04457
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 day